# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fudge < Formula
  desc "clusterfudge on the command line"
  homepage "https://clusterfudge.com"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/clusterfudgeai/homebrew-tap/releases/download/v0.1.7/clusterfudge-cli_v0.1.7_darwin_arm64.tar.gz"
      sha256 "6dac718e4d361fa6136f719ae4441db3451075a19197b2db6882f7c33757aa95"

      def install
        bin.install "fudge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clusterfudgeai/homebrew-tap/releases/download/v0.1.7/clusterfudge-cli_v0.1.7_darwin_amd64.tar.gz"
      sha256 "07db8f401410d59e2ad1d51741c7cfd48d1f05149a8423454eaa05bcd5ea4a65"

      def install
        bin.install "fudge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clusterfudgeai/homebrew-tap/releases/download/v0.1.7/clusterfudge-cli_v0.1.7_linux_arm64.tar.gz"
      sha256 "0f8c5ac038ac2751c2b104fc047d87251f4b845c35b76d388c13c9ff4e366c01"

      def install
        bin.install "fudge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clusterfudgeai/homebrew-tap/releases/download/v0.1.7/clusterfudge-cli_v0.1.7_linux_amd64.tar.gz"
      sha256 "4bd95950b9640481e624a340ef4543b1d6138d6961f80b4f65f9a9affd4a5e74"

      def install
        bin.install "fudge"
      end
    end
  end
end
