# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fudge < Formula
  desc "clusterfudge on the command line"
  homepage "https://clusterfudge.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clusterfudgeai/homebrew-tap/releases/download/v0.1.1/homebrew-tap_0.1.1_darwin_amd64.tar.gz"
      sha256 "2c15f7eb21728efd00c3b052987d7b6211bf7cabf48aa1817406d018443fd38d"

      def install
        bin.install "fudge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clusterfudgeai/homebrew-tap/releases/download/v0.1.1/homebrew-tap_0.1.1_darwin_arm64.tar.gz"
      sha256 "11583c9c2bfab3282415807535707c5db8efc8a00b190f36881aa758f3bf0138"

      def install
        bin.install "fudge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clusterfudgeai/homebrew-tap/releases/download/v0.1.1/homebrew-tap_0.1.1_linux_arm64.tar.gz"
      sha256 "13e43d5a77dfd1600c911e8075786671fb6910fe4ab07a5e8532293f699d55f7"

      def install
        bin.install "fudge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clusterfudgeai/homebrew-tap/releases/download/v0.1.1/homebrew-tap_0.1.1_linux_amd64.tar.gz"
      sha256 "d00fc14e25f2d8072f26e31b3f972bde3f2f811d9a7e6617277ca91018fc12d1"

      def install
        bin.install "fudge"
      end
    end
  end
end
